export const TIME_BLOCKS = [
    {
        timeFrom: '00:00',
        timeTo: '03:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '03:00',
        timeTo: '06:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: '',
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '06:00',
        timeTo: '09:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '09:00',
        timeTo: '12:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '12:00',
        timeTo: '14:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '14:00',
        timeTo: '17:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '17:00',
        timeTo: '20:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
    {
        timeFrom: '20:00',
        timeTo: '24:00',
        rangeRequiredFrom: 0,
        rangeRequiredTo: 0,
        carbohydrateRatioAmount: 0,
        carbohydrateRatioFor: 1,
        insulinSensitivityAmount: 0,
    },
];
